# -*- coding: utf-8 -*-
"""App_Playstore_Review.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y1hVdHV-yBrdmqLXyMVe21d5auD_Jucu

# Mengambil (Scrape) data ulasan dari aplikasi **MyTelkomsel** di Google Play Store.
"""

!pip install google-play-scraper

# Mengimpor pustaka google_play_scraper untuk mengakses ulasan dan informasi aplikasi dari Google Play Store.
from google_play_scraper import app, reviews, Sort, reviews_all

# Mengambil ulasan dari aplikasi MyTelkomsel dengan ID 'com.telkomsel.telkomselcm' di Google Play Store.
scrapreview = reviews_all(
    'com.telkomsel.telkomselcm', # ID aplikasi
    lang='id',
    country='id',
    sort=Sort.MOST_RELEVANT,
    count=1000
)

# Menyimpan ulasan dalam file CSV
import csv

with open('ulasan_myTelkomsel.csv', mode='w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    writer.writerow(['Review'])
    for review in scrapreview:
        writer.writerow([review['content']])

import pandas as pd
app_reviews_df = pd.DataFrame(scrapreview)

app_reviews_df.to_csv('ulasan_myTelkomsel.csv', index=False)

# Membuat DataFrame dari hasil scrapreview
app_reviews_df = pd.DataFrame(scrapreview)
app_reviews_df

app_reviews_df.sample(5)